version: '3'

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_notion_clipper
    image: postgres:13
    ports:
      - 5438:5432
    restart: "no"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
