"""store the full database

Revision ID: c9dca1a2fa09
Revises: d807e72bbe70
Create Date: 2021-05-26 16:09:19.140443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9dca1a2fa09'
down_revision = 'd807e72bbe70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_auth', sa.Column('database', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('notion_auth', 'database_id')
    op.drop_column('notion_auth', 'title_property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_auth', sa.Column('title_property', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notion_auth', sa.Column('database_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('notion_auth', 'database')
    # ### end Alembic commands ###
