"""initial schema

Revision ID: d11ff92eff82
Revises: 
Create Date: 2021-05-26 17:26:38.671023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11ff92eff82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('language_code', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_table('notion_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('database', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion_auth')
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
