"""title property

Revision ID: d807e72bbe70
Revises: aaf640656041
Create Date: 2021-05-26 16:03:50.161421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd807e72bbe70'
down_revision = 'aaf640656041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_auth', sa.Column('title_property', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notion_auth', 'title_property')
    # ### end Alembic commands ###
